### ISSUE TITLE
Spelling mistake - ivalid should be invalid

### ISSUE THREAD

**Issue by glomon** [metahashorg/Node-Core#2]
In Node-Core/core_service/src/main.cpp file
mostly in  DEBUG_COUT("Ivalid
![Screenshot 2020-05-07 at 10 01 35](https://user-images.githubusercontent.com/25483627/81269566-c4fabb00-9049-11ea-8747-e3927dff9a76.png)

**Comment by otselnik** [comment]
https://github.com/metahashorg/Node-Core/commit/d3a8adf0a5ae8311f33fd40fdb790ccce407ac1d
